### ISSUE TITLE
Same issue in v1 not fixed in Wallet version 2.0 release

### ISSUE THREAD

**Issue by djcaelum** [safex/wallet#26]
I am unable to recover my wallet from keys using the new version 2.0 wallet. I am trying this on a iMac as well as an Apple laptop. It immediately goes to blue screen after putting in the keys on both. Please assist.

**Comment by ddabek** [comment]
what version of osx are you on?
consider updating your OS,

Another situation had this same report, and resolved with an updated OS, in that case it was a 3 years out dated. It unrealistic that we manage to cover every single case. 

There is also command line wallet as a last resort.

**Comment by djcaelum** [comment]
Thank you for the reply, I will update my OS. My computer I use just got discontinued to be able to install Mojave. But I will run software update to insure I am running the most up to date os available for my hardware. Does the wallet run on High Sierra?

**Comment by djcaelum** [comment]
I have updated to Mojave, and the most up to date release. I am still unable to recover my wallet from keys. Any other suggestions?

**Comment by djcaelum** [comment]
Just to test functionality of the wallet, I attempted to "Create New Wallet". The software does not create a new wallet, just goes to blue screen.

**Comment by ddabek** [comment]
resort to CLI wallet if you urgently need access to your coins
https://github.com/safex/safexcore/releases/download/v0.1.2.1/safex-wallet-cli-osx

We are investigating the issue of a blue screen problem in osx. thank you for your report.

**Comment by djcaelum** [comment]
Following up as this is still an open issue. 
After running this with the console open, I am getting the following errors.
`error	06:07:27.218686 -0700	safexcashwallet	        AEGetDescData of non-desc type 'reco' not a good idea
`
`error	06:08:34.669275 -0700	safexcashwallet	errors encountered while discovering extensions: Error Domain=PlugInKit Code=13 "query cancelled" UserInfo={NSLocalizedDescription=query cancelled}
`
It would be great to get this wallet up and running for all users.

**Comment by vrgenl** [comment]
I've got the same issue running 10.13.6

**Comment by vrgenl** [comment]
Even got the same thing on fresh install ubuntu 19.04
